
spring:
  application:
    name: "customers"
#  datasource:
#    url: jdbc:mysql://localhost:3307/customersdb
#    username: root
#    password: 'root'
#  jpa:
#    show-sql: true
#  sql:
#    init:
#      mode: always
  datasource:
        url: jdbc:h2:mem:accountsdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
  h2:
      console:
      enabled: true
  jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: true
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2-console/
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8888"
build:
  version: "v0.0.2"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "customers"
    description: "Accenture Bank System Customers"
    version: "1.0.0"


